[build]
  publish = "."

[[redirects]]
  from = "/index"
  to = "/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/pdfs/*"
  [headers.values]
    Content-Disposition = "inline"
